### PR TITLE
Add ADR for checksum and filesize metadata

### PR DESCRIPTION
**Pull request by j616**
# Details
Add ADR for checksum and filesize metadata

# Pivotal Story (if relevant)
Story URL: https://www.pivotaltracker.com/story/show/187060666

# Related PRs
_Where appropriate. Indicate order to be merged._

# Submitter PR Checks
_(tick as appropriate)_

- [ ] PR completes task/fixes bug
- [ ] API version has been incremented if necessary
- [ ] ADR status has been updated, and ADR implementation has been recorded
- [ ] Documentation updated (README, etc.)
- [ ] PR added to Pivotal story (if relevant)
- [ ] Follow-up stories added to Pivotal

# Reviewer PR Checks
_(tick as appropriate)_

- [ ] PR completes task/fixes bug
- [ ] Design makes sense, and fits with our current code base
- [ ] Code is easy to follow
- [ ] PR size is sensible
- [ ] Commit history is sensible and tidy

# Info on PRs
The checks above are guidelines. They don't all have to be ticked, but they should all have been considered.

### CODE REVIEW

**Review by philipnbbc — COMMENTED** [review]
Should TAMS expose these metadata through the API, even though it or the writer clients don't generate them? How does a client get this metadata? Would a `head_url` (e.g. a pre-signed HEAD request) in the Flow Segment work if the storage backend includes these metadata in the HTTP headers?

**Comment by j616** [comment]
@philipnbbc For S3, [x-amz-checksum-mode](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax) should be set in the `GET` or `HEAD` request to the Object. I'm not a fan of adding this functionality to TAMS itself as it will increase the number of requests the API itself will have to make. One additional request per Object. The alternative is that this metadata is obtained by the client in the same request as the data. Additionally, supporting this in the API would only help with verifying downloads. As described in the ADR, verifying uploads would have to be accomplished before registering the segment. For S3, this would most likely by accomplished by [sending the checksum alongside the data](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestBody in the `PUT` request. Again, this would allow the verification and data transfer to happen in the one request. If we verified the data on `PUT` by checking the TAMS API after the fact, this could cause issues in the case that the upload is corrupted and there is a checksum miss-match. The object would have to be registered before you could retrieve the checksum and could be made available in it's corrupted state.

**Comment by philipnbbc** [comment]
> @philipnbbc For S3, [x-amz-checksum-mode](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax) should be set in the `GET` or `HEAD` request to the Object. I'm not a fan of adding this functionality to TAMS itself as it will increase the number of requests the API itself will have to make. One additional request per Object. The alternative is that this metadata is obtained by the client in the same request as the data. Additionally, supporting this in the API would only help with verifying downloads. As described in the ADR, verifying uploads would have to be accomplished before registering the segment. For S3, this would most likely by accomplished by [sending the checksum alongside the data](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestBody in the `PUT` request. Again, this would allow the verification and data transfer to happen in the one request. If we verified the data on `PUT` by checking the TAMS API after the fact, this could cause issues in the case that the upload is corrupted and there is a checksum miss-match. The object would have to be registered before you could retrieve the checksum and could be made available in it's corrupted state.

OK.  If we find that a `HEAD` request is useful to retrieve checksum and size headers then we could extend the API to have either a pre-signed HEAD request labelled "get_url", a separate `head_urls` list or a specific `head_url`.

Similarly for the PUT request, we would need to allow the client to include checksum headers in the pre-signed PUT request. It's not 100% clear to me whether a presigned URL can be created because the `x-amz-checksum-sha256` is only known / calculated by the client.

**Comment by philipnbbc** [comment]
> Similarly for the PUT request, we would need to allow the client to include checksum headers in the pre-signed PUT request. It's not 100% clear to me whether a presigned URL can be created because the `x-amz-checksum-sha256` is only known / calculated by the client.

**Review by philipnbbc — APPROVED** [review]

**Pull request merged**
